# Generated by Django 5.2.14 on 2026-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='role',
        ),
        migrations.AddField(
            model_name='borrower',
            name='department',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
