# Generated by Django 5.2.14 on 2026-05-29 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_remove_borrower_role_borrower_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='department',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowing.borrower'),
        ),
    ]
