# Generated by Django 5.2.14 on 2026-05-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0004_borrowrecord_due_time_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('late', 'Returned Late'), ('overdue', 'Overdue'), ('lost', 'Lost')], default='borrowed', max_length=20),
        ),
    ]
